[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
egui = { version = "0.21.0", features = ["serde"] }
api = { path = "../../../lib/api" }

[lib]
crate-type = ["cdylib"]
